# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: gh-pages
chart-dirs:
  - charts
chart-repos:
  - shenyu=https://erdengk.github.io/shenyu-helm-chart
helm-extra-args: --timeout 600s