apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}
    app: {{ .Chart.Name }}-{{ .Release.Name}}
  name: {{ .Release.Name}} 
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.label}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.label}}
    spec:
      containers:
      - name: shenyu-admin
        image: {{ .Values.admin.image }}:{{ default "2.4.3" .Values.admin.tag }}
        resources: {}
      - name: shenyu-bootstrap
        image: {{ .Values.bootstrap.image }}:{{ default "2.4.3" .Values.bootstrap.tag }}
        resources: {}
status: {}